name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: start_cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: ./bin/test_Polynom
    - name: make test sample list
      run: ./bin/sample_list
    - name: make test sample poly
      run: ./bin/sample_poly
