name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: start_cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: ./bin/test_Polynom
    - name: make sample list
      run: ./bin/sample_list
    - name: make sample poly
      run: ./bin/sample_poly
      
    - name: make sample hashTable
      run: ./bin/sample_HashTable
    - name: make sample avltree
      run: ./bin/sample_avltree
    - name: make sample formula
      run: ./bin/sample_formula
    - name: make sample map
      run: ./bin/sample_map
    - name: make sample mystring
      run: ./bin/sample_mystring
    - name: make sample smap
      run: ./bin/sample_smap
